sqface - Viola-Jones face detection algorithm implementation
============================================================

Introduction
------------

This project implements Viola-Jones face detection algorithm in C++ using standard Haar cascade shipped with OpenCV.
This is still an early alpha-version and a work in progress, so only one (front face) Haar cascade is supported and 
there is a lot of hardcoded limitations, mostly done in order to speed up the algorithm.

Performance
-----------

Using 512x512 full color pictures this algorithm is able to process ~3 pics per second.

OpenCV outperforms this code about 6-7 times over, but it also has a **huge** codebase.

Credits and licensing
---------------------

Author: Alexander Lubyagin, lubyagin [at] yandex dot ru

First published on December 6, 2011.

Licensed under AGPL 3.0

(At the moment) this project makes use of files licensed under the MIT license (see below):

* rapidxml.hpp
* rapidxml_iterators.hpp
* rapidxml_print.hpp
* rapidxml_utils.hpp

For third-party licenses see rapidxml/license.txt
