/* automatically generated by configure */
/* edit configure.in to change the version number */
#define SQFACE_MAJOR_VERSION 0
#define SQFACE_MINOR_VERSION 0
#define SQFACE_BUGFIX_VERSION 1
#define SQFACE_EXTRA_VERSION "-dev"
#define SQFACE_VERSION_TEXT "0.0.1-dev"
#define SQFACE_VERSION_ID 1
